### PR TITLE
Update SK translation for TWRP

### PR DESCRIPTION
**Pull request by ingbrzy**

### CODE REVIEW

**Comment by ingbrzy** [comment]
@DevUt could you push it to gerrit..?

**Comment by DevUt** [comment]
We appreciate your thought to contribute to TWRP but please use https://gerrit.omnirom.org/#/admin/projects/android_bootable_recovery to submit your changes to us

**Comment by DevUt** [comment]
@ingbrzy I can't I have not done this commit and also I have no idea what it does to the language, if you want I can help you submit to gerrit on #twrp irc

**Comment by ingbrzy** [comment]
merged

**Pull request closed without merging**
