### PR TITLE
language: add 2 new strings to IT

### PR DESCRIPTION
**Pull request by SlimShadys**

### CODE REVIEW

**Comment by sndnvaps** [comment]
you should push it to the review board.  not sent pr here 

https://gerrit.omnirom.org/

**Comment by SlimShadys** [comment]
What should I add? And where?
Il 02 apr 2016 2:39 AM, "dnv_aps sn" notifications@github.com ha scritto:

**Comment by xiaolu** [comment]
cd <project>
<make edits>
git add -A
git commit -m "commit message"
git push ssh://<username>@gerrit.omnirom.org:29418/<project> HEAD:refs/for/android-5.1

**Comment by sndnvaps** [comment]
it should be refs/for/android-6.0 now

**Pull request closed without merging**
