### PR TITLE
compatibility with cm-14.1

### PR DESCRIPTION
**Pull request by ajmtrz**
Change-Id: I9bdaa94be3dba5a76c25e690705b2a697b6814ce

### CODE REVIEW

**Comment by sndnvaps** [comment]
you'd better sent this pr to review board

**Comment by sndnvaps** [comment]
you'd better sent this pr to review board

**Comment by ajmtrz** [comment]
My english is very poor so, i don't know where either what is "pr to review board". This commit only rename libcrypto static library to libcrypto_static ( totally compatible with omnirom, aosp and cm ) and add libcrypto_utils shared library in minadbd for adb authentication ( totally compatible with omnirom, aosp and cm, too ). If you want merge it, for me ok, if not, ok too. Without this commit cm-14.1 failed to build. Thanks for TWRP.

**Comment by nailyk-fr** [comment]
Omnirom use [gerrit ](https://gerrit.omnirom.org/) as code review. Pull Request need to be send this way. 
A cm-14.1 [patch ](https://gerrit.omnirom.org/#/c/20700/) for 7.1 branch is already pending and waiting for TWRP dev approval. 
You can cherry-pick it with the download link at top-right to build on cm-14.1 until merged.

**Comment by ajmtrz** [comment]
ok. thanks. I close pull request

**Pull request closed without merging**
